[build-system]
requires = ["numpy", "setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
extend-exclude = '''
^/acat_app/gui/ui
'''

[tool.isort]
force_sort_within_sections = true
order_by_type = false
profile = "black"
skip_glob = ["acat_app/gui/ui"]